import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";
import SiteHeader from "@/components/site-header";

const fontSans = localFont({
  src: "../public/fonts/Satoshi-Variable.woff2",
  variable: "--font-sans",
});

const fontHeading = localFont({
  src: "../public/fonts/CalSans-SemiBold.woff2",
  variable: "--font-heading",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(fontSans.variable, fontHeading.variable, "font-sans")}
      >
        <ThemeProvider enableSystem attribute="class" defaultTheme="system">
          <SiteHeader />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
